version: '3.8'

services:

  app:
    container_name: fraudata_api
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      PORT: 8080
      DB_CONN: "postgres://user:password@db:5432/db?sslmode=disable"
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
    mem_limit: 500M
    cpus: 1

  db:
    image: postgres
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "db"
      TZ: 'UTC'
      PGTZ: 'UTC'
    mem_limit: 500M
    cpus: 1
